"<br>
"<div style="margin-left: 20px;"><p>You can use the following special components for file name pattern (without quotes):</p>  
"<ul style="margin-left: 20px;">
"<li> <span style="width: 40px;display: inline-block;">"/"</span>The local pathname separator </li>
"<li> <span style="width: 40px;display: inline-block;">"%t"</span>The system temporary directory</li>
"<li> <span style="width: 40px;display: inline-block;">"%h"</span>The value of the "user.home" system property</li>
"<li> <span style="width: 40px;display: inline-block;">"%g"</span>The generation number to distinguish rotated logs</li>
"<li> <span style="width: 40px;display: inline-block;">"%u"</span>A unique number to resolve conflicts</li>
"<li> <span style="width: 40px;display: inline-block;">"%%"</span>Translates to a single percent sign "%"</li>
"</ul></div>
"<br>